<a href="https://colab.research.google.com/github/najahsadmim/adult-income-prediction/blob/main/CSE422_GRP04_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**CSE422: ARTIFICIAL INTELLIGENCE**

##**PROJECT TOPIC**: ***Adult Income Prediction Using Machine Learning***

------------------------------------------------------


**SECTION 01 - GROUP 04**

**NAME               | ID**

Rayhan Jubayer Marib | 23201507

Najah Sadmim         | 24241014

##**Import Libraries**

In [14]:
#import libraries

import pandas as pd
import numpy as np

import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score, confusion_matrix, ConfusionMatrixDisplay

##**Retrieve and Display Dataset**

In [15]:
#load csv file

data = pd.read_csv('https://raw.githubusercontent.com/najahsadmim/adult-income-prediction/refs/heads/main/adult_income_dataset.csv')

data.head(5)
data.shape

(48842, 15)

##**Handle Null and Duplicate Values**

In [16]:
#replace '?' values with null values

data.replace("?", np.nan, inplace=True)

#count number of null values

data.isnull().sum()

Age                             0
Workclass                    2799
Final Weight                    0
Education                       0
Education Number of Years       0
Marital-status                  0
Occupation                   2809
Relationship                    0
Race                            0
Sex                             0
Capital-gain                    0
Capital-loss                    0
Hours-per-week                  0
Native-country                857
target                          0
dtype: int64

###**Data Imputation**

In [22]:
#null values make up of approx. 6% data only, so IMPUTE data
#workclass, occupation, native-country --> categorical values so using MODE

cols= ['Workclass','Occupation','Native-country']

impute = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

data[cols]= impute.fit_transform(data[cols])

#checking for null values after imputation
data.isnull().sum()

Age                          0
Workclass                    0
Final Weight                 0
Education                    0
Education Number of Years    0
Marital-status               0
Occupation                   0
Relationship                 0
Race                         0
Sex                          0
Capital-gain                 0
Capital-loss                 0
Hours-per-week               0
Native-country               0
target                       0
dtype: int64

###**Identifying Duplicates**

In [26]:
#count number of duplicates rows/records

data.duplicated().sum()

#drop duplicate rows

data=data.drop_duplicates()